# Generated by Django 4.2.13 on 2024-07-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(default='+380-00-000-00-00', max_length=10, unique=True),
        ),
    ]
